### PR TITLE
master: adding a static version of Night&Day

### PR DESCRIPTION
**Pull request by steveschnepp**
Note that the RRD CDEF patterns are taken from a Cacti post

### CODE REVIEW

**Comment by steveschnepp** [comment]
This needs a option to enable/disable it. Bonus would be to be able to specify the ranges, as it is currently very CET centric.

I don't think it should be per-plugin, as it might blurs the meaning

**Comment by ssm** [comment]
Add a default in Munin::Common::Defaults, and a configuration option to enable it.

**Comment by kenyon** [comment]
What does this do?

**Comment by steveschnepp** [comment]
It does put a not-white background on night periods, in order to identify daily off-patterns

**Comment by sumpfralle** [comment]
Is this change still interesting for us?

**Comment by kenyon** [comment]
> Is this change still interesting for us?

I think it would be a cool feature.

**Pull request closed without merging**
