### PR TITLE
Fix CSS validation errors & warnings

### PR DESCRIPTION
**Pull request by chteuchteu**
This PR aims to fix most CSS validation errors. There are some remaining ones though, such as 

- Property user-select doesn't exist : none
- Feature -webkit-min-device-pixel-ratio doesn't exist for media screen
- Property zoom doesn't exist : 1

These CSS properties are valid ones, and these errors can be ignored.

### CODE REVIEW

**Comment by kenyon** [comment]
OK, now @steveschnepp just needs to make the changes on the running instance on munin-monitoring.org.

**Comment by JoHartmann** [comment]
Hi @steveschnepp,
to you have make the chances to the running instance? I thing the Munin Gallery is not up to date. 
I am missing, for example, my plugin `contrib/plugins/disk/quota2percent_`. Contacting @dipohl shows the collection script works correctly.
Greetings from the home of CeBIT
Jochen

**Comment by dipohl** [comment]
Found an error in the buildscripts. Just uploaded the fixing change 1b85197ca086082cb980eecbdd0c07aeab57f2f3

**Comment by JoHartmann** [comment]
OK, now @steveschnepp just needs to make the changes on the running instance on munin-monitoring.org.

**Comment by JoHartmann** [comment]
@steveschnepp, @dipohl ,
thanks, now my plugin is online.
Greetings from the home of CeBIT
Jochen

**Pull request merged**
