### PR TITLE
fix merging field list and graph_order.

### PR DESCRIPTION
**Pull request by mtillberg**
Fix merging plugin field order with config graph_order, and apply after ds changes are in the DB.

### CODE REVIEW

**Comment by steveschnepp** [comment]
Sorry, I don't really understand what you want to do 😞

**Comment by mtillberg** [comment]
This is the munin 2.0 capability where if graph_order was undefined in the config, the order would be inferred from the order the fields are defined in the config.  Basically, the code was there, but the grep was broken.  Then, the updates to ds.ordr are moved to after the ds records are inserted.

As a side note, perl now has randomized hash iteration.  So some plugins may no longer have a stable ordering based on keys(%hash)

**Comment by yunal** [comment]
According to my memory perl never preserved order in hash iteration (I only discovered that this was a thing when I started using Ruby).

**Comment by steveschnepp** [comment]
@mtillberg oh... it does makes sense now. 

@yunal it indeed never *preserved* order, but once inside order was *deterministic* from each run. Starting in 5.18 even the [seed was randomized](https://metacpan.org/pod/perl5180delta#Hash-overhaul). 

Initially for security, but it had the nice sideeffect to expose subtle bugs such as this one.

**Comment by steveschnepp** [comment]
I analyzed it further, and actually you were mostly on spot, it is the merging that is failing.
It was not testing for equality, but for non-nullness 🤦

**Pull request merged**
