### PR TITLE
Fix fofields always having the same entries as ofields.

### PR DESCRIPTION
**Pull request by driskell**
It seems that ofields and fofields in the notification system text always list the same fields.

An example is the "df" graph, which has a field per disk. Assuming 4 disks, if one of the disks was in a WARNING state and moved to an OK state, the graph itself is marked as "state_changed". This triggers the email notification - but there is no way to know which field was fixed, ofields contains all OK fields (which in this case is all fields) - and so does fofields. In the code I can see it always sets them identical, first via `push @{$stats{$field->{'state'}}}, $fname;` and then via the check for `'ok'` which populates fofields.

This patch fixes this and makes fofields contain only entries that had a state change to OK. This seems to be the intended functionality (I assume fo = fixed ok?)

I've not been able to test this completely yet though. I copied and pasted the changes from my changes to 2.0.25 which I have installed from RedHat packages. But it should work OK.

### CODE REVIEW

**Comment by steveschnepp** [comment]
Also, you can even target the stable-2.0 branch for bugfixes, that way it will be in the next 2.0.x.

**Comment by driskell** [comment]
Absolutely. Thanks.

It's Atom - it has a really bad habit of "automatically repairing" whitespace. I'll undo the changes in Git though. I'll also rebase and modify the PR for stable-2.0 - failing that I'll reopen.

**Comment by driskell** [comment]
I've also successfully tested on 2.0 so yes, it'll much wiser that, sorry!

**Comment by steveschnepp** [comment]
Just reopen. I don't think you can change the target. And PR creation is cheap :cake:

**Pull request closed without merging**
