### PR TITLE
munin-node-configure: allow setting SNMP domain

### PR DESCRIPTION
**Pull request by kenyon**
This allows the user to probe SNMP hosts using any of the transport domains supported by Net::SNMP, by specifying the --snmpdomain option to munin-node-configure.

### CODE REVIEW

**Comment by ssm** [comment]
The tests fail with this commit.  It should be fixed before this can be merged.

If the code is OK, please update the tests

If the commit broke something, please update the code.

**Comment by kenyon** [comment]
It looks pretty easy to fix the tests. I'll try to do this when I get a chance.

**Comment by ssm** [comment]
Thanks.

**Comment by YuanDdQiao** [comment]
..I want to install munin-node on windows X64,is ok???,please ,give address for me ,please..

**Comment by kenyon** [comment]
This should be good to merge now.

**Pull request merged**
