### PR TITLE
web: remove runtime dep to fonts.googleapis.com

### PR DESCRIPTION
**Pull request by steveschnepp**
Depending on some external ressource is bad as it makes us not self
contained anymore.

Either provide the resource locally, or find an alternative

### CODE REVIEW

**Comment by steveschnepp** [comment]
@chteuchteu I resolved the conflicts in 3dfb8cd2750e34cc7c035a941f56598ac0c2aff2. Basically it's just removing all `Roboto` references. 

I don't know it's is enough or correctly done, but it achieve the main purpose of that PR : removing the dependency to something on the internet, which : 
* we don't have any control upon
* is not available when not connected on the internet

**Comment by chteuchteu** [comment]
@steveschnepp : :+1: for external resources removal.
I don't really get the difference between 3dfb8cd & f40edf9 though...

**Comment by steveschnepp** [comment]
Basically it is the same commit in different branches

**Comment by steveschnepp** [comment]
... just that the merge wasn't smooth due to external things. So it had to be handled manually.

**Comment by ssm** [comment]
The Roboto font is packaged for Debian, so if it looks better than the others, I'd leave it in front of the path of fonts.

Also, It could be useful to have the option to add external fonts, since many use externally hosted fonts. Would it make sense to add this as a configurable option?

**Comment by chteuchteu** [comment]
I planned to use Bootstrap V4's font stack (`-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif`) to pick the best available font.
I don't think making the font configurable would be great - each font would have to be tested to check that it looks fine with the UI

**Comment by chteuchteu** [comment]
(we wouldn't have to embed or load any font since this font stack covers the "prettiest" font depending on the platform)

**Comment by ssm** [comment]
I was thinking of making "use remote fonts" configurable, not the fonts themselves.

**Comment by chteuchteu** [comment]
Oh, ok.
In all cases, I think the aforementioned font stack would be enough to make the UI great on all platforms so that we wouldn't have to load any external font

**Comment by niclan** [comment]
By preference the same font in the html part of the gui and in the png files of the graphs?
Nicolai
Sendt fra min Samsung Galaxy-smarttelefon.
-------- Opprinnelig melding --------Fra: Quentin Stoeckel <notifications@github.com> Dato: 14.04.2017  19:52  (GMT+01:00) Til: munin-monitoring/munin <munin@noreply.github.com> Ko: Subscribed <subscribed@noreply.github.com> Emne: Re: [munin-monitoring/munin] web: remove runtime dep to fonts.googleapis.com (#782) 
I planned to use Bootstrap V4's font stack (-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif) to pick the best available font.

I don't think making the font configurable would be great - each font would have to be tested to check that it looks fine with the UI

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/munin-monitoring/munin","title":"munin-monitoring/munin","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/munin-monitoring/munin"}},"updates":{"snippets":[{"icon":"PERSON","message":"@chteuchteu in #782: I planned to use Bootstrap V4's font stack (`-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,sans-serif`) to pick the best available font.\r\nI don't think making the font configurable would be great - each font would have to be tested to check that it looks fine with the UI"}],"action":{"name":"View Pull Request","url":"https://github.com/munin-monitoring/munin/pull/782#issuecomment-294201581"}}}

**Comment by chteuchteu** [comment]
The font used in the PNG graphs is a monospaced font, which is great (I don't even think about managing elements position on an image file without a fixed space font)
But I don't think using the same font on the UI would be great (in a design matter)

**Comment by sumpfralle** [comment]
I would like to revive this discussion in order to get rid of this external resource.

I prepared another pull request based on the discussion above. Please take a look: #965

**Comment by sumpfralle** [comment]
The alternative proposal #965 was merged - thus the issue seems to be closed.

**Pull request closed without merging**
