### PR TITLE
Silence autoconf errors

### PR DESCRIPTION
**Pull request by cgzones**
Adjust several plugins, so that munin-node-configure does not complain about any.

### CODE REVIEW

**Comment by sumpfralle** [comment]
Thank you for taking the time to fix issues of the `autoconf` procedure!

Most of your changes look good to me.

But the removal of the `autoconf` flag from the postgresql-related plugins is probably not correct, since these plugins use `Munin::Plugin::Pgsql`. This module handles `autoconf` requests.
Thus there is no need to remove the `autoconf` attribute, or?

And could you please apply your changes to the `stable-2.0` branch instead?

**Comment by cgzones** [comment]
reworked the pgsql driver instead

**Comment by cgzones** [comment]
I opened #1001  for the stable branch; this master pr in addition fixes the squid plugin, which is not existent in the stable branch

**Comment by cgzones** [comment]
Removed all stable commits

**Comment by sumpfralle** [comment]
cool - thanks!

**Pull request merged**
