### PR TITLE
fix warning on node list operation

### PR DESCRIPTION
**Pull request by cgzones**
stable pr of #998

### CODE REVIEW

**Comment by sumpfralle** [comment]
looks good, thank you!

**Comment by cgzones** [comment]
I do not know

There are some differences in `_list_services` between master and stable regarding the `$node` usage:

stable
```
my ($session, $node) = @_;
$node ||= $config->{fqdn};
if (exists $nodes{$node}) {
    my @services = @{$nodes{$node}};
```

master
```
my ($session, $node) = @_;
if (keys %nodes == 1 && ! exists $nodes{$node}) {
    # Only one node. Naming mismatch. Just give the use what he wants.
    ($node) = keys %nodes;
}

if (exists $nodes{$node}) {
    my @services = @{$nodes{$node}};
```

Maybe the line ```$node ||= $config->{fqdn};``` needs to be reintroduced?

**Comment by sumpfralle** [comment]
> Maybe the line $node ||= $config->{fqdn}; needs to be reintroduced?

Yes, indeed I think, this is the proper behaviour for an `undef` input: we really want to get rid of the possibility of `undef` as early as possible.

Thus we could revert the above change for `stable-2.0` and reintroduce the above line to `master`.

Do you agree?

**Comment by cgzones** [comment]
Yes, this would make sense

**Comment by sumpfralle** [comment]
Done - also see a3ca1531.

**Comment by cgzones** [comment]
Can you revert the `undef` to `''` change?

**Pull request merged**
