### PR TITLE
httpd: adding some preforking

### PR DESCRIPTION
**Pull request by steveschnepp**

### CODE REVIEW

**Comment by steveschnepp** [comment]
@ssm `HTTP::Server::Simple::CGI::PreFork` is missing from debian right now, that's why I didn't merge it et, and assigned it to you instead.

**Comment by colinmollenhour** [comment]
Would this improve page load performance? E.g. I have ~20 servers and the load-hour sparklines take a long time to load. Thanks!

**Comment by chteuchteu** [comment]
Yes it would indeed. For now, the resources (main page, assets (CSS and JS), graphs) are served one after the other by the server. 

Adding preforking would allow parallelising requests and hence make the pages loading much faster - especially on multicpu servers.

**Comment by colinmollenhour** [comment]
I merged this locally and got it to build and wow what a huge difference. I'm glad I found this PR!

**Comment by bjoe2k4** [comment]
How about including a (*very much to the need of munin-httpd*) stripped down version of `HTTP::Server::Simple::CGI::PreFork` into `munin-httpd`?

**Comment by colinmollenhour** [comment]
So is preforking not going to be supported or is this already present in a different branch?

**Comment by dipohl** [comment]
The closing happened by accident. Steve made a mistake in the last IRC meeting

> 20:29:16 * h01ger hopes TheSnide did the push origin :devel by now
> 20:29:37 h01ger: we agreed last meeting to get rid off it
> 20:29:41 TheSnide: h01ger: not yet. i'm deeply late one that
> 20:29:52 h01ger: do it now ;)
> 20:33:41 hugin: steveschnepp pushed 1 new commit to master: https://git.io/vX24L
> 20:33:41 hugin: master 14203a421 Steve Schnepp: Merge remote-tracking branch 'origin/devel'...
> 20:35:40 hugin-dev [munin] steveschnepp pushed 1 new commit to devel: https://git.io/vX2Be
[by that many PR were closed by devel removal..]
> 20:36:28 TheSnide ouch..

Full chat protocol: http://meetbot.debian.net/munin/2016/munin.2016-11-09-20.21.log.html

**Comment by colinmollenhour** [comment]
Ahh. It's easy to make such mistakes, I'm sure. :) However, can someone reopen this ticket so it isn't forgotten? Thanks!

**Comment by dipohl** [comment]
it can't get reopened as the branch devel was removed. You have to open a new pull request addressing recent branch master.

**Pull request merged**
