### PR TITLE
[plugins] remove linux specific df plugin

### PR DESCRIPTION
**Pull request by cgzones**
The linux df plugin uses multigraph for displaying the different devices.
This means that for each device a new graph is generated.
The standard df plugin combines all devices like the df_inode plugin into one single graph.
I think this is a more compact way.

p.s.: currently the multigraph support is also broken, cause a dot instead of an underscore is used as seperator.

### CODE REVIEW

**Comment by steveschnepp** [comment]
It would be better to convert it to a hierarchical plugin than to remove it

**Comment by cgzones** [comment]
But what is then the advantage of this plugins in comparison to the generic df one?

**Comment by cgzones** [comment]
Maybe rename the linux `df` plugin to something like `df_detailed` (so that the default `df` plugin is also installed) and set the family to `contrib` (so that it's not enabled by default)?

**Comment by sumpfralle** [comment]
While I appreciate trivial and non-conditional plugins, I very much dislike code duplication. Thus I would really prefer to avoid adding another copy of existing code with slight deviations :(

**Comment by sumpfralle** [comment]
Closing in order to avoid code duplication.

**Pull request closed without merging**
